- Editor/ServiceProfileInspector.cs
Currently when a new service profile is created the properties inside the profile are not exposed.
The changes allow the custom properties to be visible in the editor without the need of creating a new custom profile
Update the custom inspector to expose any custom properties.
Before
After
> Update custom profile to allow custom properties to be visible

- .github/workflows/buildupmpackages.yml
- Editor/PropertyDrawers/PlatformEntryPropertyDrawer.cs
- Editor/ServiceManagerInspector.cs
- package.json
Resolved two issues reported on the Service Framework:
- https://github.com/realitycollective/realitytoolkit.dev/issues/36
- https://github.com/realitycollective/realitytoolkit.dev/issues/35
- Fixes: [](https://github.com/realitycollective/realitytoolkit.dev/issues/35)
- Fixes: [](https://github.com/realitycollective/realitytoolkit.dev/issues/36)
- 
None
* Tested manually
* Updated pipeline to do platform builds
> Feedback issue resolution & build automation

- Editor/PropertyDrawers/ProfilePropertyDrawer.cs
- Editor/PropertyDrawers/ServiceDisplayEditor.cs
- Editor/ServiceManagerInspector.cs
Addressing some issues raised in testing:
Resolves: https://github.com/realitycollective/realitytoolkit.dev/issues/38
Fixes: Added exception catching on the Profile Object selector as the functionality is broken in 2021 (works in 2020?)
> Issue resolution from testing

- Editor/ServiceProfileInspector.cs
Addresses an issue found in the custom editor of the service profiles not allowing editing of the custom fields exposed.
- Fixes: https://github.com/realitycollective/realitytoolkit.dev/issues/37
> Fixing Read-only Properties

- Editor/PropertyDrawers/ServiceDisplayEditor.cs
- Editor/ServiceManagerInspector.cs
- Editor/ServiceProfileInspector.cs
- Runtime/Definitions/Profiles/ServiceProvidersProfile.cs
- Runtime/Services/ServiceManager.cs
- Runtime/Utilities/ServiceManagerInstance.cs
- Added exception handling for fringe cases
- Resolved issue where Service Manager was not being instantiated in the Inspector
- Added protection to prevent adding a second Service Manager Instance in a scene
- Misc fixes
> Service Improvements for the framework and protection on use.

- Editor/ServiceWizard.cs
- Runtime/Definitions/Profiles/ServiceProvidersProfile.cs
- Runtime/Services/ServiceManager.cs
- Runtime/Utilities/ServiceManagerInstance.cs
Aligned both editor and runtime names to "Service Framework"
- Updated editor menu path to state "Service Framework"
- Updated Asset menu path to "Service Framework"
-
> Aligned both editor and runtime names to "Service Framework"

- Editor/ServiceManagerInspector.cs
Updated the profile label for the Service Framework Instance inspector screen
> Inspector name update

- Editor/PropertyDrawers/PlatformEntryPropertyDrawer.cs
- Editor/ServiceProfileInspector.cs
Added tooltips to service configuration
> Added tooltips to service configuration

- Editor/ServiceWizard.cs
Update service wizard to handle projects with names including spaces, which is used as the default namespace for a new service.
> Update Service Wizard to handle spaces in Project name which is used as the default for a new service namespace

- Runtime/Services/ServiceManager.cs
Ensure EventSysetm exists as soon as an event service is registered
> Ensure EventSysetm exists as soon as an event service is registered

- Editor/ServiceManagerInspector.cs
- Runtime/Utilities/ServiceManagerInstance.cs
Make an internal API of the ServiceManagerInstance public so that scripted initiailzation is possible (hint: Toolkit configure).
Also removed 2 unnecessary pings on profiles.
> Enable programmatically initializing the service manager

- Editor/ServiceManagerInspector.cs
Remove redundant double check on Profile being null
> Remove redundant double check on Profile being null

- .github/workflows/buildupmpackages.yml
- .github/workflows/publishpackages.yml
- Editor/ServiceFrameworkPreferences.cs
- Editor/ServiceWizard.cs
- Editor/Utilities/EditorMenuUtilities.cs
- Editor/Utilities/EditorMenuUtilities.cs.meta
- package.json
Updated build cycle to do full test in PR and then automatically release on merge to development.
Includes new editor feature to add the service manager in to a scene
> Update to release cycle plus feature

- .github/workflows/publishpackages.yml
> Minor patch to build script

- Editor/ServiceProfileInspector.cs
The existing Service Framework base Service Inspector forced overriding in OnInspectorGUI.  This has now been updated to provide a better and more controlled experience with a custom override RenderConfigurationOptions method
> Update Service Inspector Overriding

- Runtime/Extensions/TypeExtensions.cs
Removes any non `IService` types from the potential candidate list for service interface types.
> Exclude non-service types from interface type candidates

- package.json
> Up Version for Release 1.0.1 - no-ver

- Runtime/Services/ServiceManager.cs
Resolves issue with corrupted arrays in destroying services
- Service Manager destroy loop changed to not use a copy of the array on destroy.
> PR to address corrupted activeService array when destroying services

- Editor/BaseProfileInspector.cs
- Editor/ServiceFrameworkPreferences.cs
- Editor/ServiceManagerInspector.cs
- Editor/Utilities/ServiceFrameworkInspectorUtility.cs
- Runtime/Services/ServiceManager.cs
- package.json
Several cleanup tasks in preparation for next release.
- Remaining MixedReality references remove/updated
- Remaining System -> Service references removed/updated
- Documentation updates
- Update Utilities dependency
> Minor update and clean-up tasks

- .github/workflows/development-buildandtestupmrelease.yml
- package.json
Update build workflow to use the multi unity version build and test script
> Switch test step to multi-version build

- Editor/ServiceFrameworkPreferences.cs
- package.json
Updating the Service Framework tool to fit under the asset store version of the Reality Toolkit
Temporary redirect placed in existing location until the next full release for consumers
> Update Editor menus

- package.json
clearing tags and resetting dev back to 1.0.4
> clearing tags and resetting dev back to 1.0.4

- README.md
Update readme to boost 1_5 release
> Update readme to boost 1_5 release

- Editor/Utilities/EditorMenuUtilities.cs
- Runtime/Services/ServiceManager.cs
- Runtime/Utilities/ServiceManagerInstance.cs
> Address Unity 2023 warnings

- Editor/ServiceWizard.cs
- package.json
Resolves: #81
Update Service Wizard to cache Generation path
- Fixes: https://github.com/realitycollective/com.realitycollective.service-framework/issues/81
> Update Service Wizard to cache Generation path

- Documentation~/com.realitycollective.service-framework.md
- README.md
- package.json
> Rename .io to .net
